# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install1
      run: cd /tmp;git clone https://github.com/libbpf/libbpf.git;cd libbpf;cd src;pwd;sudo make;sudo make install;sudo apt install -y linux-tools-$(uname -r);
    - name: Install2
      run: bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h;go mod download;go generate;go build -v -o bin/eBPFeXPLOIT
      

