# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install1
      run: sudo apt install -y make clang llvm libelf-dev libbpf-dev bpfcc-tools libbpfcc-dev
    - name: Install2
      run: sudo apt install -y linux-tools-$(uname -r) linux-headers-$(uname -r) linux-tools-common
    - name: Install3
      run: bpftool btf dump file /sys/kernel/btf/vmlinux format c > ./ebpf/vmlinux.h;

    - name: Install4
      run: uname -a;go generate;ls;

    - name: Install5
      run: go build -v -o bin/eBPFeXPLOIT-linux-amd64
      
    - name: test
      run: sudo bin/eBPFeXPLOIT-linux-amd64 --help
    - name: upload result
      uses: actions/upload-artifact@v2
      with:
        name: eBPFeXPLOIT-linux-amd64
        path: ./bin/eBPFeXPLOIT-linux-amd64


