# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install1
      run: sudo apt install -y make clang llvm libelf-dev libbpf-dev bpfcc-tools libbpfcc-dev
    - name: Install2
      run: sudo apt install -y linux-tools-$(uname -r) linux-headers-$(uname -r) linux-tools-common
    - name: Install3
      run: bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h;

    - name: Install4
      run: ls;rm ebpf_bpfel_arm64.go;rm ebpf_bpfel_arm64.o;ls;go generate;go build -v -o bin/eBPFeXPLOIT
      

